version: 2.1

orbs:
  gusto: gusto/gusto@0.0.9

jobs:
  test:
    executor: gusto/ruby-2-3
    steps:
      - gusto/bundle-install
      - run: bundle exec rspec

workflows:
  main:
    jobs:
      - test
